### ISSUE TITLE
Windows does not find the Updated_Randomizer.py File

### ISSUE THREAD

**Issue by SuicuneSigma** [lashoun/upgraded-fefates-randomizer#1]
I've carried out steps 1-6 as directed, but the randomizer file itself seems to have not been run when typing into the command console. Trying to get the settings from the Python file does work, however.

![Capture](https://user-images.githubusercontent.com/49259766/118199450-62808b80-b410-11eb-9c83-c91494b11d90.PNG)

I used the included GGG files (the recommended ones), have not touched any of the files included in the download aside from moving RandomizerSettings to data, and have installed all the relevant environments needed. Not quite sure what's going wrong.

**Comment by lashoun** [comment]
Sorry for the late answer! That's my bad, I forgot to add the extension of the script in the first command: you're supposed to type `python updated_randomizer.py`. I fixed the readme too. Since the second command works, the first should too!

**Comment by lashoun** [comment]
Closing the issue for now; feel free to reopen it if needed!
