### ISSUE TITLE
ImportError: cannot import name default_rng

### ISSUE THREAD

**Issue by SchmoogCriminal** [lashoun/upgraded-fefates-randomizer#12]
When I try to run the 'python updated_randomizer.py' command I get the message "ImportError: cannot import name default_rng". I'm new to Python so I'm not really sure what's wrong or what to do about it. Pretty sure I got pip, numpy, and xmltodict successfully installed and opened CMD using the folder's address bar, which I think is the correct way to go about it, but any help would be appreciated.

**Comment by SchmoogCriminal** [comment]
Ok, I think this particular issue involved the version of numpy (1.16.6) so I've tried instead switching to a higher version of Python and numpy (3.16 and 2.1.1), but that gives me a different issue: "UnicodeDecodeError: 'cp932' codec can't decode byte 0x93 in position 455: illegal multibyte sequence", which I understand means I need to figure out how to make Python read it using a different code (if that's the term), so I'll see if I can't figure that out before I get a response.

**Comment by SchmoogCriminal** [comment]
I finally managed to fix it; I was on a non-English locale and that caused either the format or characters used in python to change to something that was unreadable.

**Comment by lashoun** [comment]
Hi, sorry for not coming to your help sooner. Thank you for posting your solution. I hope you will enjoy your run!
