### ISSUE TITLE
Character named "Sakura" not found.

### ISSUE THREAD

**Issue by MrMostache** [lashoun/upgraded-fefates-randomizer#4]
Hello,
I'm trying to randomize Vanilla JPN Special edition. Conquest route and Join order is selected.
Steps 0-6 in the README goes smoothly. At step 7 when I ask python to run the updated randomizer, I receive the error Character named "Sakura" not found. Sometimes I get Subaki or Hana instead.

Any idea would be helpful.

**Comment by lashoun** [comment]
Hey, did you give the tag `-g "Conquest"` to the randomizer? If you don't, it checks for characters which are not in your route.

**Comment by MrMostache** [comment]
It seems -g "Conquest" is not a recognized command in the randomizer.
I typed     python -g "Conquest"  ,  and     -g "Conquest"    too.
 
Another question I have is building the files back. I use FEAT to decompress all the files, but when rebuilding the ISO, huge errors in the game show. Is there way to decompress only the files that the randomizer care about?

**Comment by lashoun** [comment]
Sorry if that was not clear: you need to type `python updated_randomizer.py -g "Conquest"`. If you look further down for the example of custom run, you can see how arguments can be passed to the randomizer.

As for FEAT, I believe the four folders all need to be edited... But you indeed do not need to decompress any other folders in the romfs.

Why do you need to rebuild the ISO though? Use something like layeredFS, it's much simpler.

**Comment by MrMostache** [comment]
Thanks for the reply.

Ok, I think I understand how the argument works. I have to type in all the options in one line, banning the stuff that I didn't include in the randomizer settings.

I needed to decompress some of the files, as I'm dumping my own RomFS which results in a lot more folders ( that the randomizer doesn't need). Using the randomizer 5.5 will tell me that some files are missing such as GameDate.bin which I fix by decompressing that file. I understand the layeredFS method, but I'm wondering which folders to copy paste in the mods folder.

**Comment by lashoun** [comment]
When opening the randomizer jar file, did you tick the "Japanese version" option?

As for the folders, in point 2 of the Readme's installation instructions, you can find:

> Make sure that the selected folder has folders named `castle`, `GameData`, `m`, `Scripts` directly inside it.

In other words, those 4 folders are the folders you need to decompress, and only them.

Hope that helps. The readme should have most of the information you need.

**Comment by lashoun** [comment]
Closing the issue, feel free to reopen if needed!
