### ISSUE TITLE
ValueError: Character named "Shigure" not found

### ISSUE THREAD

**Issue by Juggalopff** [lashoun/upgraded-fefates-randomizer#7]
I tried following the instructions best I could, and things seemed to have worked fine up till starting the updated_randomizer.py program. When I do so i begins to work but then quits out with the error that "Shigure" is not found. I'm not sure what I should do from here.

This is what I'm left with:

![git](https://user-images.githubusercontent.com/104796159/166326186-22dc9705-b169-435b-bd30-5b5e2fd9cf48.png)

**Comment by lashoun** [comment]
You probably did not check the "Randomize children" option with the jar file and need to run the command with the `-bc` tag (for "ban children"). Try running `updated_randomizer.py -bc`.

**Comment by lashoun** [comment]
Closing, feel free to reopen if needed.
