### ISSUE TITLE
Python command not going through

### ISSUE THREAD

**Issue by AiChan94** [lashoun/upgraded-fefates-randomizer#9]
I followed the instructions and got Python and everything working, then I followed the og randomizer instructions 
- Dumped the files through Citra as it was one of recommended options from the randomizer
- Went with the Upgraded version
- Ran the randomizer, it goes through just fine
- When I then try to run the python command (I went with python updated_randomizer.py -ab -ads -dbsr -dlts -dlsc -ds -dsr -edbc -egd -erps -g "Revelations" -gsmax 350 -gsmin 280 -mc 2. At first I had an error in the options (wrote -ebdc instead of -edbc) and it asked me to fix it, so I did) it gives me this error

Traceback (most recent call last):
  File "C:\fates\updated_randomizer.py", line 1989, in <module>
    fatesRandomizer = FatesRandomizer(
                      ^^^^^^^^^^^^^^^^
  File "C:\fates\updated_randomizer.py", line 656, in init
    self.randomizeAllClasses()
  File "C:\fates\updated_randomizer.py", line 1336, in randomizeAllClasses
    self.randomizedClasses[characterNames2[i]] = className
                           ~~~^^^
IndexError: list index out of range

I tried various different settings for the randomizer but no matter what settings I used I am still getting this error
Friend of mine also attempted to look into it and mentioned an empty file (characterNames2) and that it removes 5 people from the class randomization with jakob, felicia and azura being constant three and 2 other being random, I'm not sure if this could help point out to the solution but thought I can as well mention it

**Comment by lashoun** [comment]
Hey, thanks for the issue, I'll have a look at it this afternoon!

**Comment by lashoun** [comment]
Ok, it should be fixed! There were a few small coding errors for cases I usually do not encounter since my settings are different from yours. Please pull the changes with `git pull` from inside the repository, confirm that it works and close the issue if that is the case!

Also, I'll reword the README since if you use Upgraded Fates you do not need to dump your own romfs at all.
